# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('photologue', '0011_auto_20160306_1016'),
        ('cmsplugin_photologue_pro', '0003_auto_20150917_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('per_page', models.IntegerField(choices=[(0, 'All'), (10, 10), (25, 25), (50, 50), (100, 100), (250, 250)], default=100, verbose_name='Photos per page')),
                ('photos_to_show', models.IntegerField(default=6, verbose_name='Photos to show')),
                ('template', models.CharField(choices=[(b'cmsplugin_photologue_pro/gallery_plugin.html', b'Default'), (b'cmsplugin_photologue_pro/carousel_v1.html', b'Carousel V1'), (b'cmsplugin_photologue_pro/fancybox_small_thumbs.html', b'Fancybox small thumbs')], default=b'cmsplugin_photologue_pro/album_plugin.html', max_length=250, verbose_name='Template')),
                ('show_photo_title', models.BooleanField(default=True, verbose_name='Show photo title')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Gallery')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='album',
            name='album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
